# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         ./_sass
  style:            :compressed

# Site settings
title: A few words from an avid HTMLer
subtitle: jasoncorns.com
email: contact@jasoncorns.com
description: > # this means to ignore newlines until "baseurl:"
  Wandering the world of code design and application architecture, absorbing all the Creative opportunities in this
  wonderful industry of ours.
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
timezone: America/Los_Angeles
future: true
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
disqus_shortname: 
reading_time:     true
words_per_minute: 200

# Owner/author information
owner:
  name:           Jason Corns
  avatar:         1789_10151376948874753_1728718603_n.jpg
  bio:            "I'm a father, husband, Lego builder, golfer, BBQ enthusiast, Chili lover and legal US Citizen."
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        jasoncorns
  facebook:       
  github:         JasonAllenCorns
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
