# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WanderingCreative
subtitle: A few words from an avid HTMLer
email: contact@jasoncorns.com
description: > # this means to ignore newlines until "baseurl:"
  Wandering the world of code design and application architecture, absorbing all the Creative opportunities in this
  wonderful industry of ours.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jasoncorns
github_username:  resentedHook

# Build settings
markdown: kramdown
