# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         ./_sass
  style:            :compressed

# Site settings
title: jasoncorns.com
subtitle: A few words from an avid HTMLer
email: contact@jasoncorns.com
description: > # this means to ignore newlines until "baseurl:"
  Wandering the world of code design and application architecture, absorbing all the Creative opportunities in this
  wonderful industry of ours.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jasoncorns.com" # the base hostname & protocol for your site
timezone: America/Los_Angeles
future: true
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
